import './globals.css';
import React from 'react';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Users/sogawa/work/lab/supabase-with-nextjs-13/public/favicon.ico" />
      </head>
      <body>{children}</body>
    </html>
  );
}
