import './globals.css';
import React from 'react';

import Link from 'next/link';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Users/sogawa/work/lab/supabase-with-nextjs-13/public/favicon.ico" />
      </head>
      <body>
        <header>
          <Link href="/"> top </Link>
          <Link href="/signup"> signup </Link>
          <Link href="/signin"> signin </Link>
        </header>
        <hr />
        {children}
      </body>
    </html>
  );
}
