-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER EXTENSION pg_graphql
    UPDATE TO "0.5.0";

ALTER EXTENSION pgsodium
    UPDATE TO "3.0.6";

REVOKE ALL ON TABLE public.articles FROM authenticated;
REVOKE ALL ON TABLE public.articles FROM postgres;
REVOKE ALL ON TABLE public.articles FROM service_role;
GRANT ALL ON TABLE public.articles TO authenticated;

GRANT ALL ON TABLE public.articles TO postgres;

GRANT ALL ON TABLE public.articles TO service_role;
